server:
  port: 9100
spring:
  main:
     allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clients_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: admin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
feign:
  hystrix:
    enabled: true
   
keycloak:
  realm: formation-ms
  auth-server-url: http://localhost:8080/auth
  resource: client-app
  credentials:
    secret: 78e26af4-7d64-43f7-9dd8-e6e37700a6aa
  principal-attribute: preferred_username
  bearer-only: true

swagger-ui:
  client: swagger-ui
  secret: 5cd64901-ad75-4def-bcb5-1b8bf05d84bf
  