server:
  port: 9101

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bogad/omni-formation-ms.git
          #uri: file:///C:/Users/Abouaggad/Desktop/Formation MS/github/formation-ms
